# Generated by Django 5.1.4 on 2026-05-24 21:38

import api.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_column="PublicId", default=uuid.uuid4, unique=True
                    ),
                ),
                (
                    "email",
                    models.CharField(db_column="Email", max_length=255, unique=True),
                ),
                (
                    "password",
                    models.CharField(db_column="PasswordHash", max_length=255),
                ),
                (
                    "full_name",
                    models.CharField(db_column="FullName", default="", max_length=255),
                ),
                (
                    "position",
                    models.CharField(db_column="Position", default="", max_length=255),
                ),
                (
                    "department",
                    models.CharField(
                        db_column="Department", default="", max_length=255
                    ),
                ),
                ("role", models.CharField(db_column="Role", default="", max_length=50)),
            ],
            options={
                "db_table": "Users",
                "managed": False,
            },
            managers=[
                ("objects", api.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="Name", max_length=255)),
                ("description", models.TextField(db_column="Description", default="")),
                (
                    "status",
                    models.CharField(
                        db_column="Status", default="Active", max_length=50
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, db_column="StartDate", null=True),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, db_column="EndDate", null=True),
                ),
            ],
            options={
                "db_table": "Projects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("name", models.CharField(db_column="Name", max_length=255)),
                (
                    "category",
                    models.CharField(db_column="Category", default="", max_length=255),
                ),
                ("is_active", models.BooleanField(db_column="IsActive", default=True)),
            ],
            options={
                "db_table": "Skills",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserProject",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("joined_at", models.DateTimeField(db_column="JoinedAt")),
            ],
            options={
                "db_table": "UserProjects",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserSkill",
            fields=[
                (
                    "id",
                    models.AutoField(db_column="Id", primary_key=True, serialize=False),
                ),
                ("level", models.CharField(db_column="Level", max_length=50)),
                ("created_at", models.DateTimeField(db_column="CreatedAt")),
                (
                    "updated_at",
                    models.DateTimeField(blank=True, db_column="UpdatedAt", null=True),
                ),
            ],
            options={
                "db_table": "UserSkills",
                "managed": False,
            },
        ),
    ]
